# Generated by Django 5.1.4 on 2025-01-03 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_gardener_visitrequest_client_confirmation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitrequest',
            name='gardener',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_visits', to='appointments.gardener', verbose_name='Jardinero Asignado'),
        ),
    ]
